name: feature CI

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch dev branch
        run: |
          git fetch --unshallow origin dev:dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: 'false'

      - name: Install dependencies
        run: go mod tidy

      - name: Detect changed Go packages
        id: detect-packages
        run: |
          merge_base=$(git merge-base dev HEAD)
          changed_files=$(git diff --diff-filter=AM --name-only "${merge_base}"..HEAD | grep '\.go$' || true)

          if [ -n "$changed_files" ]; then
              changed_packages=$(echo "$changed_files" | xargs -n1 dirname | sort -u | sed 's/^\.$/./')
              echo "Changed packages:"
              echo "$changed_packages"
              {
                echo "CHANGED_PACKAGES<<EOF"
                echo "$changed_packages"
                echo "EOF"
              } >> "$GITHUB_ENV"
          else
              echo "No Go files changed."
          fi

      - name: Run tests in changed packages
        run: |
          if [ -z "$CHANGED_PACKAGES" ]; then
            echo "No Go files changed, skipping tests"
          else
            IFS=$'\n'
            for pkg in $CHANGED_PACKAGES; do
              echo "Running tests in $pkg"
              go test -v "./$pkg"
            done
            unset IFS
          fi
